GET http://localhost:3000/subscribers



###



GET http://localhost:3000/subscribers/644d212cf12490b2eb410b02



###


POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Dude",
    "subscribedToChannel": "web dev simplified"
}


###


DELETE http://localhost:3000/subscribers/644d1eddd0a01e18003e3e77

###


PATCH http://localhost:3000/subscribers/644d212cf12490b2eb410b02
Content-Type: application/json

{
    "name": "New Name"
}